Fixed parent directory crashing
schismtracker/schismtracker pull request #451
Opened 2024-05-28 13:40 UTC by HanaMcHanaface

On windows the parent directory ".." would show when browsing files, even if a parent directory doesn't exist. Selecting that option would crash ST. With this fix the ".." doesn't show up if there's no parent directory. Also added a bunch of checks when getting the parent dir. Needs to be tested on linux since I only use windows.

2024-05-28 16:49 UTC, mrpapersonic requested changes

2024-05-28 16:49 UTC, mrpapersonic commented on schism/util.c
> +	if (!dirname || strlen(dirname) == 0)
`!dirname[0]` does the same thing here without the overhead of calling strlen()

2024-05-28 16:49 UTC, mrpapersonic commented on schism/util.c
> +	if(strlen(ret) == 0) return NULL;
same comment as above

2024-05-28 16:49 UTC, mrpapersonic commented on schism/util.c
> +			n--;
```c
while (n > 0) {
    if (dirname[--n] == DIR_SEPARATOR)
        break;
}
```
would be a bit cleaner here IMO

2024-05-28 16:49 UTC, mrpapersonic commented on schism/util.c
> +	}
Curly braces aren't necessary here

2024-05-28 18:23 UTC, HanaMcHanaface commented
@mrpapersonic Hmm I'm getting now compilation errors which seem related to what you're working on.

![image](https://github.com/schismtracker/schismtracker/assets/113458072/de2c1c99-fee9-47c1-94dc-ea5f5321dc9d)

Any idea what's happening?

2024-05-28 18:26 UTC, HanaMcHanaface commented
Okay I don't have all the commits in git gotta try that first.

2024-05-28 18:29 UTC, HanaMcHanaface commented
Nope still no worky with the latest commit

2024-05-28 22:21 UTC, mrpapersonic commented
Whichever compiler I was using let me convert `char**` to `uint8_t**` implicity but it doesn't work under yours for some reason. (btw, you'll want to run autoreconf and configure again because I changed those a bit)

2024-05-28 23:47 UTC, HanaMcHanaface commented
ohh gotcha. Idk I'm just using msys2 mingw 64-bit and running make. Just like it said in docs. Btw I think you forgot to push

2024-05-28 23:57 UTC, HanaMcHanaface commented
Anyways I managed to build just adding the casts and hope the code is good now.

2024-05-29 03:07 UTC, mrpapersonic commented
> ohh gotcha. Idk I'm just using msys2 mingw 64-bit and running make. Just like it said in docs.

Yep, it's just weird cause I wasn't getting those errors on windows. Maybe I just have an outdated msys2.

2024-05-29 07:12 UTC, merged